### ISSUE TITLE
mobile: visual pagination error occurs on  search results pages

### ISSUE THREAD

**Issue by BrutiAnteneh** [CityOfBoston/boston.gov-d7#1214]
**URL tested:** https://www.boston.gov/search?page=2&query=tickets&

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+8&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.boston.gov%2Fsearch%3Fpage%3D2%26query%3Dtickets%26&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.boston.gov/search?page=2&query=tickets&) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone 8 |
| Browser | Mobile_safari |
| Operating System | iOS 11.0 |
| Resolution | 750 x 1334 px |
| Screen size | 4.7 in - 2.64 x 5.44 in |
| Viewport | 375 x 667 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/3f37e8c45e2e184565f3bff3158e5de35957384b/realios_iPhone_8.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/3f37e8c45e2e184565f3bff3158e5de35957384b/realios_iPhone_8.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+8&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fwww.boston.gov%2Fsearch%3Fpage%3D2%26query%3Dtickets%26&speed=1&host_ports=google.com%2C80%2C0&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://www.boston.gov/search?page=2&query=tickets&) to reproduce the issue on Browserstack:**

**Comment by jimafisk** [comment]
So it looks like we're doing a `display: none;` on the `pg-li-i-h` class (has the "previous" and "next" language) for mobile. If we indeed want to hide the "previous" and "next" text for mobile, then we need to target the parent `<li>` not the actual `<span>`. It's a little tricky because the `.pg-li-i--a` class also corresponds to the highlighted page (2 from the screenshot above). We'll want to use something like a `first-of-type` and `last-of-type` pseudo class to hide just the "previous" and "next" and its background color / padding.
