### ISSUE TITLE
Updates to metrolist:

### ISSUE THREAD

**Issue by jimafisk** [CityOfBoston/boston.gov-d7#1339]
1. limit cases published on https://www.boston.gov/metrolist/affordable-properties to rental listings only, no resales. This should be accomplished by filtering in only those records that have "Lottery type" set to "Rental" on the Salesforce record. Not sure how filter is currently set up.

2. Add resales to https://www.boston.gov/metrolist/lottery-and-resale. This is sort of the opposite problem -- on this page we DO want ownership opportunities (this page represents actual openings and is well-maintained) but the filtering is too restrictive, which is forcing the program manager to futz with the Salesforce record in a way that compromises accuracy in order to fit the code

3.  Allow sorting by Location as well as Zip code on https://www.boston.gov/metrolist/affordable-properties

4. Offer technical assistance to Gary Battiston in his attempts to enable grid entries on the listing form: https://www.boston.gov/metrolist/metrolist-listing-form

*Matt,Jim, Susanna, Gary Battiston*

**Comment by jimafisk** [comment]
Many of the records in our database have blank "Lottery Type" field. If we're looking for a specific "Rental" value, all of these partial records are going to be filtered out as well. We could filter out records with specific values, but in looking through the data there are a bunch of potential values for this field:
- Ownership
- Resale
- Rental Post Lottery
- Rental

I'm curious if this is being populated from a standardized list of values or if it's free-form, which would make it a little more difficult. We could show all "Rental" and blank records if that's desired.

**Comment by SusannaRH22** [comment]
Lottery field: yes, no, no answer, unknown
Lottery type: Rental, ownership, resale, rental post lottery. The field name is a bit of a misnomer; this is really just indicating the housing type category. It's either a rental or an ownership opportunity, and either new or old/existing. "Rental" means new rental (initial lease-up), ownership means new ownership unit, resale means old/existing ownership unit, rental post lottery means old/existing rental).
Resale: yes, no, no answer, unknown

The Lottery type field is a standard list of values selected via drop down, yes.

On the lottery & resales pages we want to, naturally, show lotteries and resales. Lotteries can be rental (new or existing) or ownership (only new). There are no lotteries for resales which is why we want to be sure not to include them on this page.  

Essentially, a record should be published to the Lottery&Resale page if Lottery= yes OR if Resales=yes. Resales should be filtered out of the Affordable Properties page. So, we could use the "Resale" field instead of the "Lottery type" field for filtering purposes.

I can explain better in person. It's kinda confusing, not least because the site separates listings into three sections. I'm very open to whatever works-- I was probably too prescriptive in my ticket write-up. Let's discuss this afternoon.

**Comment by jimafisk** [comment]
From our discussion today, here are some action items:
1. We need to add a new boolean field for "resale" to the Metrolist Affordable Housing object in Drupal: `/admin/structure/types/manage/metrolist_affordable_housing/fields`
2. We need to add a salesforce mapping for the new resale field: `/admin/structure/salesforce/mappings/manage/metrolist_affordable_housing`
3. We need to add a filter group to the lottery view (`/admin/structure/views/view/metrolist_affordable_housing/edit/page_1`) so records appear on https://www.boston.gov/metrolist/lottery-and-resale if lottery = yes OR resale = yes.
4. We need to add field rewrite logic to the lottery view (`/admin/structure/views/view/metrolist_affordable_housing/edit/page_1`) so the "Listing Information" column should have link text that represents the type of info being presented. The link text "Lottery Info" should display if `field_mah_lottery_indicator` = true, it should say "Resale Info" if the new "resale" field = true, and if both the lottery and resale fields happen to be true, it should default to "Resale Info".
5. We would like to add exposed filters for "search" and "neighborhoods" on https://www.boston.gov/metrolist/lottery-and-resale similar to what is currently on https://www.boston.gov/metrolist/affordable-properties

I have already implemented the first item of the requested changes per https://github.com/CityOfBoston/boston.gov-d7/pull/1340. The https://www.boston.gov/metrolist/affordable-properties page now has additional filters: Lottery Type = "Rental" or is blank. @SusannaRH22 is checking to see if another OR condition should be added for "Rental Post Lottery"
