### ISSUE TITLE
Update media module

### ISSUE THREAD

**Issue by matthewcrist** [CityOfBoston/boston.gov-d7#512]
Need to update media module to rc12. Once updated verify that all behat tests pass.

- [ ] **Media** updated to 7.x-2.0-rc11 from 7.x-2.0-beta1, located at sites/all/modules/contrib/media

**Comment by BrutiAnteneh** [comment]
@jimafisk tried to work on this but the tests kept failing.

PR that Jim opened but was never committed found here: https://github.com/CityOfBoston/boston.gov/pull/1048

We need another person to take a look.

**Comment by jimafisk** [comment]
This seems to be related to this issue: https://www.drupal.org/project/media/issues/2841742

So the tests will pass if you comment out any line that has the permission `administer media wysiwyg view mode` in "sites/default/settings/permissions.settings.php"

<details>
  <summary>Extra context for folks (click to expand)</summary>

If you want to test behat locally, you can do so when running your local build like so:
`./task.sh -Dbehat.run-server=true build:test`

Alternatively you can run behat without building the site: `/var/www/boston.gov/vendor/bin/behat  --config=/var/www/boston.gov/tests/behat/local.yml --tags=~@hub --format=pretty --format=junit  --out=std --out=/var/www/boston.gov/reports  --profile=local --strict --verbose --colors`

But it won't help in this case since the permissions need to be built from `sites/default/settings/permissions.settings.php`

If you see an error like this:
`exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: self signed certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in /var/www/boston.gov/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:187`

It's because your local SSL/TLS cert is not trusted, a quick fix is to just turn off this check locally by editing `/var/www/boston.gov/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php` and on line 333, just set it to false: `$conf[CURLOPT_SSL_VERIFYPEER] = false;`

If you get an error like this: `cURL error 51: SSL: no alternative certificate subject name matches target host name 'hostname'`

You just need to make sure your FQDN is correct, so you can just reissue your cert: `openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/apache-selfsigned.key -out /etc/ssl/certs/apache-selfsigned.crt`

</details>
